@startuml "contextual-work-comm.png"

Package WorkContext {

  class ContextualCommWork {
  contexts : ContextualCommWorkTask[]
  communication : Communication.Communication
  context : WorkContext.WorkContext
  }

  note top : Comm participants are all users of all Tasks

  class ContextualCommWorkTask {
  name : string
  description ?: string
  contexts : ContextualCommWorkTaskUser[]
  communication : Communication.Communication
  context : WorkContext.WorkTaskContext
  }

  note right : Comm participants are all users of the Task

  class ContextualCommWorkTaskUser {
  users : ContextualComm.ContextualCommUser[]
  communication : Communication.Communication
  context : WorkContext.WorkTaskUserContext
  }

  note right : Comm participant is user


  ContextualCommWork -|> ContextualComm.CompositeContextualComm

	ContextualCommWork *-down- "0..*" ContextualCommWorkTask

  ContextualCommWorkTask -|> ContextualComm.CompositeContextualComm

	ContextualCommWorkTask *-- "0..*" ContextualCommWorkTaskUser

	ContextualCommWorkTaskUser -|> ContextualComm.AtomicContextualComm
}
@enduml
