@startuml "work-context-design.png"

  class WorkContext {
  contexts : WorkTaskContext[]
  communication : communication.communication
  context : context.context
  }

  note top : Comm participants are all users of all Tasks

  class WorkTaskContext {
  contexts : WorkTaskUserContext[]
  communication : communication.communication
  context : context.context
  }

  note right : Comm participants are all users of the Task

  class WorkTaskUserContext {
  user : ContextualComm.ContextualCommUser[]
  communication : communication.communication
  context : context.context
  }

  note right : Comm participant is user


  WorkContext -|> ContextualComm.CompositeContextualComm

	WorkContext *-down- "0..*" WorkTaskContext

  WorkTaskContext -|> ContextualComm.CompositeContextualComm

	WorkTaskContext *-- "0..*" WorkTaskUserContext

	WorkTaskUserContext -|> ContextualComm.AtomicContextualComm

@enduml
